  version: '3'
  services:
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      ports:
        - "8081:8080"
      volumes:
        - /opt/zigbee2mqtt_maison2/data:/app/data
        - /opt/zigbee2mqtt_maison2/udev:/run/udev:ro
        #- ./data:/app/data
          #devices:

      environment:
        - TZ=Europe/Paris
        - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://${HA_IP}:${PORT_MQTT_ONE}
        - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt_maison2
        - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=tcp://${ZIGBEE_POE_DONGLE}:${PORT_ZIGBEE_DONGLE}
      restart: always
      network_mode: host
      privileged: true
